### ISSUE TITLE
Version 5

### ISSUE THREAD

**Issue by hn1** [pqina/filepond#1012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

There are too many issues with version 4

### Describe the solution you'd like

**We would like the issues in v4 rectified and version 5 released asap.**

Hi
We have raised a few issues and they seem to have 'MAGICALLY' disappeard!

You keep saying this is free and if you don't like it use something else.

At the same time, you say if you want to help the development/maintenance of this library then by the Pintura library - **WHICH WE HAVE**.

So in fact - for us and anyone else who has purchased the Pintura library, this is **NOT FREE** as it is an integral part of an image management solution for the end user.

Conidering this is a **PAID** product, having to put up with more than 50 bugs and the arrogant responses is really unprofessional.

Also, even if it was free (for those who have not invested in Pintura), the open surce community does have some expectation that whoever is advertising their work, it should be to a standard worth investing their time, resources (which ultimately means **NOT FREE**).

**Take a note of LINUX, ELASTCSEARCH etc. etc. etc.**

So can we have version 5 published so that we can get on with our job.
Thanks.

### Describe alternatives you've considered

At this time, we are trying to stick with the FilePond and Pintura but it is becoming more and more painfull.

**Comment by rikschennink** [comment]
You can find your issue here:
https://github.com/hn1

As far as a I can tell, all of them have been answered. One isn’t because you refused to format your code snippets. If you don’t feel like investing time, it’s probably not important enough.

_If_ you purchased a license then you can reach out to paid support, I’m more than happy to help.

I can’t believe you think it’s okay to communicate the way you have in the tickets you opened on this repo.

This is all I’m going to reply here.
