### ISSUE TITLE
restoring state after page submit

### ISSUE THREAD

**Issue by kmanley** [pqina/filepond#13]
I have a page with the filepond control and some other controls.
Suppose the user uploads a couple files, and the filepond control shows them in green.
Then the user submits the page and there is a validation error, so all the controls are shown again.
My server knows the current state of the uploads; how can I update the filepond UI on the client to show the files that were uploaded previously?

**Comment by rikschennink** [comment]
It's best to use the `files` property for this when creating the FilePond instance. It can be configured to restore server files. See [Setting initial files](https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files) for instructions.

**Comment by kmanley** [comment]
Thanks, this is really helpful and it's working. 
The only issue now is when I do this the file size is displayed as "1 KB". Is there a way I can just hide the file size for files that were previously uploaded before the page refresh?

**Comment by rikschennink** [comment]
@kmanley Good point, I'll run some tests on Monday, will get back to you on this (currently there's no way to disable file size).

**Comment by rikschennink** [comment]
Hi @kmanley, does your server return the **content-length**, **content-type** and **content-disposition** headers? You can see them implemented in the `handleRestore` method of the [PHP API](https://github.com/pqina/filepond-boilerplate-php/blob/3aaf16db6121ac471eb3f600ec52c043747637fe/public/api/index.php#L85).

FilePond uses these headers to determine what file it has just restored.

**Comment by DrTF** [comment]
restor mutiple files failed ! Only echo the last file's name.

**Comment by rikschennink** [comment]
Hi @DrTF, can you share your options object?

**Comment by DrTF** [comment]
The circumstance like this.
1. create form： upload multiple file to server. And Database save file infos use **JsonArray**.
2. modify form:  I want to use  **modal_info** (**springmvc**) directly that with the **JsonArray**.
3. like this 
![image](https://user-images.githubusercontent.com/11496772/38240150-644826d2-3761-11e8-839a-4853b44a6b00.png)
4. The method **server.load** only return true. Because I just want to display "file_name" and 
 delete the file_name.  Then I can only update **JsonArray**...

**Comment by rikschennink** [comment]
Hi!

You need to set the files as a property of the options object, `addFiles` is for adding new files.

```js
FilePond.create({
    files: files,
    server: {
        load: 'xxxx/xxxx/load'
    }
});
```

**Comment by NichAga** [comment]
@rikschennink And, is there a possibility to inject an already uploaded file wihout re-create the isntacen everytime?

Thanks.

**Comment by rikschennink** [comment]
I'm not sure I follow @NichAga

**Comment by NichAga** [comment]
@rikschennink I have a modal, where there is my filepond instance. The problem is that I use the same modal for multiple insert/modify of multiple elements (for example X restaurants). Everytime I open the modal, I do a "removeFiles()" to remove all the files from the filepond instance, but I seems to not find a solution for insert some files of this X resturant that I previously uploaded. (When I open the modal, I do an ajax request to get the info of this resturant, and I also have all ther server ids of the images, of course)

**Comment by rikschennink** [comment]
I think setting the `files` property with your previously uploaded files should work.

**Comment by NichAga** [comment]
The files property of the filepond instance?
Example, I have the filepond instance already created long time ago as `this.filepond`
I enter the modal, and I do a `this.filepond.files = [...]` ?

**Comment by rikschennink** [comment]
Yes, it should update the file list with the newly supplied files

**Comment by NichAga** [comment]
Thanks @rikschennink , gonna try it this evening.

**Comment by gianpietro1** [comment]
Hi @rikschennink, what happened to the [Setting initial files](https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files) section? Thanks!

**Comment by rikschennink** [comment]
You can now find it here: https://pqina.nl/filepond/docs/api/instance/properties/#files
