### ISSUE TITLE
No update On the UI when moved to different browser tab

### ISSUE THREAD

**Issue by picxydev** [pqina/filepond#239]
First of all.. great plugin. Thanks to the authors.

Here is what noted.
1. Uploaded 10 photos (options --- parallel uploads:10, max uploads: 50)
2. I see some uploading percentage on all the files ( say 20%). 
3. Now, I go to another tab on the browser ( do some browsing)
4. Until I come back to my upload screen, the progress percentage is not changing.. though files received & processed by server.

**Comment by rikschennink** [comment]
Thanks for the video. It looks like the files are uploaded correctly, and the UI is updated correctly as well. If I understand correctly it's that the problem is that it waits with picking up the next item till the tab is focussed? If so, that is a known issue and should be improved in the near future. As this is related to FilePond core the issue has been moved here.

**Comment by pbaggiol** [comment]
Experiencing this same issue.  Also in Chrome.
Do you know when there might be a fix available for this?

**Comment by rikschennink** [comment]
@pbaggiol "near future"

**Comment by rikschennink** [comment]
Just published version `4.4.5` which switches the internal event loop to be based on `setTimeout` instead of `requestAnimationFrame` when a tab is inactive. Please confirm this fixes the issue @pbaggiol @picxydev

**Comment by przelu** [comment]
Works for me now, thank you!

**Comment by JaimeBtab** [comment]
Hello again, 

I am using the last version 4.11.0 of plugin and I am having same issue as the beggining of this incident. Maybe the problem is repeating again with another later change? Is it working ok again?

I am using Google Chrome as default.

**Comment by JaimeBtab** [comment]
Hello, I updated the plugin to 4.13.0 and tested in Chrome and Firefox and the issue is still happening. 

I've checked the code changed in that version and I would like to know if it is possible to change the duration or time of setTimeout value to reduce it.


```
var setTimerType = function setTimerType() {
			if (document.hidden) {
				requestTick = function requestTick() {
					return window.setTimeout(function() {
						return tick(performance.now());
					}, interval);
				};
				cancelTick = function cancelTick() {
					return window.clearTimeout(id);
				};

			} else {
				requestTick = function requestTick() {
					return window.requestAnimationFrame(tick);
				};
				cancelTick = function cancelTick() {
					return window.cancelAnimationFrame(id);
				};
			}
		};
```

**Comment by rikschennink** [comment]
@JaimeBtab Looking into this now

**Comment by rikschennink** [comment]
We can't lower the `setTimeout` interval, it's 16ms right now, on inactive tabs it's automatically set to a higher value by the browser (Chrome prevents values lower than one second).

After running some tests, I find this functionality is still working. What is happening is that FilePond will wait with uploading files till all animations have finished (this is to prevent hick-ups in the animations). BUT animations keep running when the tab is inactive, which means they're updated one frame per second (instead of 16) this causes major delays in between files and one major delay before the first file upload starts.

I've updated the animation logic to only run when the document is active. If the document is inactive/hidden the animations will automatically jump to their end states (this makes sure the interface looks correctly when re-activating a document). This seems to solve the issue and greatly increases the speed at which background uploads are handled.

Version 4.13.2 that fixes the issue is now available.

**Comment by JaimeBtab** [comment]
Hi @rikschennink! 

I'm just doing tests and it's working nice when tab is not active , thanks!

In long list of files, the animation remains Uploading 100% (in blue state) and do not change to Upload Complete (in green state). It is not a major issue because the real state is correctly Uploaded for those files and when the entire list is uploaded the process ends. It's just a issue to keep in mind.

![image](https://user-images.githubusercontent.com/46215333/79108789-5e022300-7d77-11ea-9061-55f216a0a5ed.png)

Thanks again for quick answer

**Comment by rikschennink** [comment]
@JaimeBtab Glad to hear that 👍

> In long list of files, the animation remains Uploading 100% (in blue state) and do not change to Upload Complete (in green state). It is not a major issue because the real state is correctly Uploaded for those files and when the entire list is uploaded the process ends. It's just a issue to keep in mind.

I can't reproduce this.

**Comment by rikschennink** [comment]
@JaimeBtab I forgot to push 4.13.2 to npm so please make sure you've got the latest version to test with.

**Comment by JaimeBtab** [comment]
Yes @rikschennink, I had the last version 4.13.2 when I tested. 
Thanks for consideration !

**Comment by EthosData** [comment]
Hi @rikschennink 

Thanks for the fix!

My testing it, we have seen that when uploading the files while the tab is inactive, there is a significant difference in terms of upload. As you mention, there is an increase on delay.

Here is an example on comparison between uploading with active tab (top) and inactive (down): 
![image](https://user-images.githubusercontent.com/59917489/79209823-d16d6880-7e3b-11ea-9921-eda9011f0b5b.png)

You say it is because it is taking a timer set by the browser. Is this something that we can bypass? I can see other similar plugin does not have such dependency on the browser timer and it would be great if we can achieve that!

I believe you set that timer in here, right?. Can it be modified?:
![image (1)](https://user-images.githubusercontent.com/59917489/79210089-35902c80-7e3c-11ea-89a3-6b3a3d8aec71.png)

**Comment by rikschennink** [comment]
From the screenshot it's difficult to tell the actual delay between files. I've got an idea what might be causing it, I'll take a look.

**Comment by rikschennink** [comment]
@EthosData Should be improved in `4.13.3`

**Comment by EthosData** [comment]
Thank @rikschennink 

We applied the change but still we see big delays. Can you let me know the improvement you have done for the last version?

To show better what I am referring to, I have done a short video showing the gaps of the delays while being inactive the tab: [Video.zip](https://github.com/pqina/filepond/files/4475505/Video.zip)

**Comment by rikschennink** [comment]
@EthosData Can you make sure you're on `4.13.3` and you're cache is cleared.

**Comment by EthosData** [comment]
Yes, we have checked it twice and we are in 4.13.3 plus doing the tests after clear cache from browsers (Chrome, Firefox and Edge).

**Comment by rikschennink** [comment]
@EthosData okay, double checking.

**Comment by rikschennink** [comment]
@EthosData fixing. We're getting there. Try `4.13.4`

**Comment by EthosData** [comment]
@rikschennink 

This version has now fixed. Now seems there is no delays with the tab is inactive. 

Thanks a lot!

**Comment by pbaggiol** [comment]
I can confirm.  This has resolved the issue for me too.
