### ISSUE TITLE
Addfile fires before hidden input is populated by file-encode plugin

### ISSUE THREAD

**Issue by rijkvanzanten** [pqina/filepond#28]
Hi! Awesome work on this plugin, I love it 😄 

I'm trying to dynamically render the preview image (using the base64 string) outside of the plugin. In order to achieve this, I'm trying to get the base64 string as soon as it's ready so I can update my preview. However, it seems like the `FilePond:addfile` event fires _before_ the hidden input is created (let alone ready) and `FilePond:processfile` doesn't seem to fire at all..?

How can I access the information in the hidden input when a file is added? Is there a special event for when the file-encode plugin is ready?

My attempt:

```js
FilePond.registerPlugin(FilePondPluginFileEncode);

// original input[type=file]
var input = document.querySelector('input');

// upgrade file input to filepond
FilePond.create(input);

var pond = document.querySelector('.filepond--root');

pond.addEventListener('FilePond:addfile', function() {
    // Element doesn't exist yet
    console.log('No element: ', pond.querySelector('input[name="filepond"]'));
   
    setTimeout(function () {
      // Now the element exists and the value is accessible
      console.log('Value: ', pond.querySelector('input[name="filepond"]'));
    }, 5000);
});

pond.addEventListener('FilePond:processfile', function(event) {
    // Doesn't seem to fire at all?
    console.log('Nothing..', event);
});
```

https://codepen.io/RijkvanZanten/full/QmJLZv

**Comment by rijkvanzanten** [comment]
Maybe the `file-encode` plugin could emit an event when the worker is done?

```js
applyFilterChain('PREPARE_OUTPUT', file, {
   query: query,
   item: item
})
  .then(function(file) {
    var worker = createWorker(DataURIWorker);

    worker.post({ file: file }, function(data) {
      root.ref.data.value = JSON.stringify({
        id: item.id,
        name: file.name,
        type: file.type,
        size: file.size,
        metadata: item.getMetadata(),
        data: data
      });
      // Here ? 
      document.dispatchEvent(
        new CustomEvent('FilePond:encoded', { detail: plugin$1 })
      );

    });
  })
  .catch(function(error) {
    console.error(error);
  });
```

https://github.com/pqina/filepond-plugin-file-encode/blob/4b39b31c3bf735903bf75a2ff0334eca297af7b2/dist/filepond-plugin-file-encode.js#L71-L91

**Comment by DamSenViet** [comment]
Ah I understand. The problem here is that when the FileReader object is called to read in the data uri, it does it ASYNCHRONOUSLY. You have to wait for the readIn to finish before it's ready.

Also your `pond.processFile()` only works when you set the `server` option when you create the object or when you `setOptions`. As default, it will attempt to upload or `processFile()` when you drop in a file / add a file unless you specified `instantUpload: false`. Check out the docs.

**Comment by rijkvanzanten** [comment]
Ahhh gotcha! I didn't realize from the docs that the process events were for server only. I think this boils down to the feature request for an event onencode  :)

**Comment by rikschennink** [comment]
Hi @rijkvanzanten and @DamSenViet !

I would like the `addfile` event to fire after the file has been encoded, having a separate file encoded event might be a bit confusing, also, is another plugin does some other alterations on the file we'd need another event to track when it's done. 

The file encode action is currently run after the load of the file, which causes the event to fire before the encoding is done. What makes this tricky is that the File Encode plugin will have to apply any output transforms ( resizing, cropping ) which are only applied when the interface is in an idle state ( otherwise these actions would block the UI ). 

I'm looking to creating a hook that allows plugins and other heavy internal processes to be run at certain moments without interfering with the normal flow of the events.

- add file ( drop, browse or use api )
- create file item
- get file data ( could be on a remote server )
- get file data progress
- file loaded
- apply file transformations ( this needs to happen when the interface is idle, but should ideally be skipped when no transformations are required )
- addfile event!

**Comment by DamSenViet** [comment]
I recommend giving us access to the FileReader object. It's native to JavaScript and we could just get the data from the hidden input by detecting a success from the readIn.

**Comment by rikschennink** [comment]
@DamSenViet I'd consider that a suboptimal solution as it would require devs to have knowledge of FilePond's internal systems in order to use the file encode plugin. Whether you're uploading async or encoding files, the `addfile` event should be fired when the file has been fully added. Using plugins should be as easy as registering them and setting some options, seamless. 

If you do need access to the FileReader you can fork the file-encode plugin and add a callback option to the configuration object.

**Comment by DamSenViet** [comment]
For now as a temporary solution. I here's what I did to detect whether the encoding is finished.


```
flagChecker = null;
function beginUpload() {

    // only one repeating interval should exist at any time for uploading (assuming you only want to upload one file) 
    if (flagChecker !== null) {
        clearInterval(flagChecker); // perfectly safe to clear null
    }

    // set flagChecker to the interval id
    flagChecker = setInterval(function() {
        if ($('input[name="filepond"]')[0].value !== "") {
            callbackfunction();
            clearInterval(flagChecker);
        }
    }, 300);
};


```

**Comment by rikschennink** [comment]
@rijkvanzanten @DamSenViet Just published version `1.2.11` of FilePond and `1.0.4` of the File Encode plugin. Should fix the issue.

**Comment by DamSenViet** [comment]
Awesome and thank you so much! Will you be updating the npm modules too?

**Comment by rikschennink** [comment]
@DamSenViet Noth npm modules have been updated as well.
