### ISSUE TITLE
url.split is not a function

### ISSUE THREAD

**Issue by rovansteen** [pqina/filepond#289]
### Summary

I'm noticing errors popping up occasionally when initialising Filepond with an existing file, causing the `getFileNameFromURL` method to call `split` on the `url` even though it's undefined.

### How to reproduce
Initialise Filepond (React) like so
```jsx
<Filepond
  files={{
      source: "id",
      options: {
        type: 'local'
      }
  }}
/>
```
It now tries to fetch the file by using the ID and the configured backend URL.
Randomly it will fail to properly get the url from the request and call `getFilenameFromURL` with `undefined`.

I haven't found a reproducible case where this always happen, it just seems to happen "randomly", perhaps due to a timing issue? In all of these cases the server returned with a `200` status code and the image.
 
### Expected behaviour
To always get the correct url if the request itself is successful. 

### Additional information
Filepond version `4.2.0`
It happens on a variety of devices, ranging from mobile to desktop, from Mac to Windows.

**Comment by rikschennink** [comment]
Is this the same file each time?

**Comment by rovansteen** [comment]
Nope, mostly different files

**Comment by rikschennink** [comment]
maybe it's a problem with the content-disposition header?

**Comment by SalesforceMark** [comment]
I have the same issue, what's the suggested workaround?

**Comment by rikschennink** [comment]
@SalesforceMark If you can supply a test case that reproduces the issue I'm happy to take a look.

**Comment by SalesforceMark** [comment]
False alarm, just wasn't supplying the init data correctly.

**Comment by otheabould** [comment]
Same issue here, when preloading 2 or more images, randomly, one of them will fail to load. Send help

**Comment by otheabould** [comment]
Has anyone managed to fix this?

**Comment by rikschennink** [comment]
@otheabould If you can supply a test case on https://codesandbox.io I'm happy to take a look. You can use this template one as a starting point: https://codesandbox.io/s/vanilla-filepond-2oltb

**Comment by Keltin42** [comment]
I ran into this same issue, and just spent several days fighting with it.  What I am trying to do is disable the buttons on a form while an image is being processed and uploaded to my service.  On the surface, this would seem quite easy, there are several lifecycle callbacks you can register for.

I don't have a simple sandbox test case for you, but I can tell you exactly how to reproduce the error.
1. Create a ReactJS App
2. Use the filepond wrapper and example code from the documentation:  https://pqina.nl/filepond/docs/patterns/frameworks/react/
3. Add handlers for any of these callbacks:  `beforeAddFile`, `onaddfile`, `onprocessfilestart`.  Within that handler, update the state of the react object, eg.
`this.setState({uploading: true});`
4.  Witness the error.

I haven't looked deeply into the filepond code, but here is what I think is happening.  The "addfile" process is operating asynchronously, the react setState() causes another render() call to occur before the "addfile" process is completed.  This render essentially initiates *another* "addfile" process with the current value of this.state.files, and this one ends up creating the error we see.

If you comment out the setState() you added, you'll see that `onupdatefiles` is called twice, but with setState() there it gets called three times, and one time through it is a Blob object not a File object, and that seems to cause the exact error.  Note that it is also weird that `onupdatefiles()` is called twice on what should be "normal operation", so that got me thinking ...

If you remove `{files}` completely from the `<FilePond>...` definition, then I only see one call to `onupdatefiles()`, and everything seems to operate perfectly fine.  So this just seems to be an issue with using a FilePond object as a "managed react object".

**Comment by rikschennink** [comment]
@Keltin42 Thanks for testing. I'll look into this further when I have some time.

**Comment by rikschennink** [comment]
@Keltin42 You're right that the issue is probably related to "syncing" state between React and FilePond's internal file items list. It's not perfect and I'm open to suggestions on how to improve this.

**Comment by Keltin42** [comment]
@rikschennink Yeah, I'm not positive about the best way to fix it either.  I have two ideas that I was going to look at: 

1. Capture some of the Filepond callbacks and block updates between, for instance, `onaddfilestart` and `onupdatefiles`.  This is basically creating a "state machine" to manage when to do updates and when to block them.  I don't understand enough of the Filepond use cases to know if that is going to cause other problems though, my usage has been very simple.

2. A more complicated solution would be to block users of the class from setting the `files` property on the Filepond object, and to implement within the class a local files property that uses the events to keep it up to date and exposes callbacks to clients to let them know when the value has been updated.  This is essentially creating an "intermediary" between the Filepond files property and what React classes get access to.  This one would be a lot more work, and I'm not 100% convinced it solves the problem.

I'm working on some other things right now, so I don't have a chance to experiment with these ideas.  I'd like to come back to this, but it'll probably be several months.

**Comment by rikschennink** [comment]
@Keltin42 Thanks! No worries, I appreciate the feedback and ideas. 👍

**Comment by dominiqueh** [comment]
Has there been any updates around this issue? I've run into it and will post if I find a solution.

**Comment by rikschennink** [comment]
very much appreciated @dominiqueh
