### ISSUE TITLE
Feature Idea? Store image(s) as Blob in state/localStorage

### ISSUE THREAD

**Issue by danielimmke** [pqina/filepond#399]
Hello, Filepond is great but for my purposes I don't actually want to upload an image until a larger form is submitted. Wanted to ask if this is something that might be on the roadmap where the UI of uploading is the same but it actually just stores the file as a [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) and you can send it as data when the form is submitted.

Apologies if this is already possible and I just didn't pick up on it from reading documentation!

**Comment by rikschennink** [comment]
@danielimmke this should be possible with a custom `server.process` method, where instead of sending the file to the server you generate an id for the file store the file in localStorage or indexedDB with that id and return the id of the file to FilePond. You could then restore this file with the given id by implementing the `server.restore` end point.

**Comment by danielimmke** [comment]
Thanks! I will close.

**Comment by huaj2008** [comment]
@rikschennink could you kindly provide a sample code for this?

**Comment by tutuk-flowdesk** [comment]
@rikschennink  Hello i'm pretty new to programming. I am coding with React Hooks and trying to solve this problem. Can you maybe show me a little example for this custom `server.process`?

**Comment by rikschennink** [comment]
@tutuk-flowdesk better to ask this on Stack Overflow

**Comment by tutuk-flowdesk** [comment]
@rikschennink  okay, thank you for that fast answer.
