### ISSUE TITLE
Revert url is only called after chunk uploads are complete, not during uploads?

### ISSUE THREAD

**Issue by prince272** [pqina/filepond#433]
Revert url is only called after chunk uploads are complete and you press the delete button. Is there a way to during chunk uploads processing when cancelled.

**Comment by rikschennink** [comment]
I believe currently there is not.

**Comment by jcohen02** [comment]
Hi @rikschennink, is this behaviour by design? I noticed this while working on chunked upload support for the Python Django filepond backend.

At present, if a chunked upload fails after uploading some number of chunks, you can retry or cancel the upload. If you cancel, as @prince272 has pointed out, the upload disappears from the filepond UI but no call is made to the server to notify it of the cancellation. This potentially results in a number of chunk files of a partially completed and then cancelled upload floating around on the server.

If there is no specific design reason for not making a revert call when cancelling a partially complete chunked upload, I could potentially have a go at adding this to filepond, along with an option to switch the functionality on, if you'd prefer the default case to remain as is.

Thanks.

**Comment by rikschennink** [comment]
@jcohen02 Would be a nice addition, I wouldn’t mind if it was default.

**Comment by jcohen02** [comment]
Ok, thanks @rikschennink, happy to take a look at this but its likely to take a few days for me to get round to this.

**Comment by rikschennink** [comment]
@jcohen02 no worries, take your time 👍

**Comment by jcohen02** [comment]
@rikschennink it would be useful to get your thoughts on the implementation of this feature - I'm still trying to familiarise myself with the design of filepond. I can see you've put a lot of work into the library design and so I'd like any update to stick within the current model. I can see a few different ways to solve this but any advice on which you think is the most suitable would be useful.

**What's the issue?**

When a user is uploading a file, if the upload fails (potentially after automatic retries), the user sees the file object in the UI with the red bar and two options - the "x" on the left hand side to cancel the upload or the retry button on the right hand side. If the "x" is clicked, the upload is cancelled, however, if a chunked upload was taking place and 1 or more chunks have been successfully uploaded, this may leave partially uploaded file data stored on the server disk.

**What do we want to achieve?**

If a chunked upload was taking place and one or more chunks have been successfully uploaded, when the button is clicked to cancel the upload, a revert request should be sent to the server so that the server-side has the opportunity to remove any stored file data relating to the cancelled upload.

**Some possible implementation options:**

 - In the `REMOVE_ITEM` handler in `actions.js`, add an additional branch to the [if statement (from L884)](https://github.com/pqina/filepond/blob/044a7ca00393b6f03cf732ae61a2ce6a876ad8a1/src/js/app/actions.js#L884) to check if the upload is chunked and if one or more chunks have been successfully uploaded, dispatch a `REQUEST_REVERT_ITEM_PROCESSING` event to revert the upload. However, this results in `REVERT_ITEM_PROCESSING` being called and another `REMOVE_ITEM` being dispatched so we get into a loop! This could be solved by forcing `state.options.instantUpload` to be `false`. This prevents dispatch of another REMOVE_ITEM event but it feels like a hack so I don't think this is the right way to solve things.

 - The above option could possibly be solved by adding a `chunkedUpload` boolean parameter to the `REQUEST_REMOVE_ITEM` logic and then using this to trigger the revert event, passing the `chunkedUpload` parameter through to `REVERT_ITEM_PROCESSING` and using this to prevent `REMOVE_ITEM` being triggered again in this case. Again this doesn't feel quite right.

 - Another possibility may be to create a different button handler associated with a button with a new ID (but the same icon) that is displayed when a chunked upload fails. This would trigger a different event, say `REQUEST_REMOVE_CHUNKED_ITEM` which would in turn dispatch `REVERT_CHUNKED_ITEM_PROCESSING`. This would revert the upload without triggering `REMOVE_ITEM` since this is handled by the original event dispatch.

Hope this makes sense! Thanks.

**Comment by rikschennink** [comment]
@jcohen02 appreciate the detail, will get back to you asap, currently swamped with work.

**Comment by jcohen02** [comment]
No worries @rikschennink, whenever you get the chance.

**Comment by rikschennink** [comment]
@jcohen02 I think option 1 would be best, if we can prevent the looping situation (I think we can by calling `item.revert` instead of dispatching the revert request. 

I've added reverting for limbo/input files in the past two releases to fix another issue, it might have "magically" fixed this as well (not sure haven't tested). If not, I think calling `item.revert` will solve the loop issue.
