### ISSUE TITLE
How to prevent from dropping the same file in jQuery?

### ISSUE THREAD

**Issue by allgrowsm** [pqina/filepond#556]
Hello,

Is it possible to prevent from droping the same file?

I have following set up in my enviroment and try to not drop the same file.

```
  const inputElement = document.querySelector('input[type="file"]');
  FilePond.registerPlugin(
    FilePondPluginImagePreview,
    FilePondPluginImageExifOrientation,
    FilePondPluginFileValidateSize,
    FilePondPluginImageValidateSize,
    FilePondPluginFileValidateType,
  );
  FilePond.setOptions(labels_JA);
  FilePond.setOptions({
      require: true,
      allowDrop: true,
      allowReplace: false,
      allowRevert: false,
      maxParallelUploads: 1,
      checkValidity: true,
      dropValidation: true,
      instantUpload: true,
      allowImagePreview: true, 
      imagePreviewMaxHeight: 100,
      maxFiles: 20,
      imagePreviewMarkupShow: false,
  });
  FilePond.create( inputElement,
  {
    acceptedFileTypes: ['image/png','image/jpg','image/jpeg','video/avi','video/mp4','video/mov','video/mpeg','video/wmv','video/mkv'],
  });
```
Best regards,

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

If your issue can be classified as an integration question or a question about specific features of FilePond we ask you kindly to submit it on [Stack Overflow](https://stackoverflow.com/questions/tagged/filepond).

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the template is not filled out or if the issue is determined to be a question.
