### ISSUE TITLE
what are the other return parameters in custom server functions?

### ISSUE THREAD

**Issue by subodhk01** [pqina/filepond#558]
<img width="433" alt="Screenshot 2020-08-27 at 04 23 21" src="https://user-images.githubusercontent.com/19875783/91364730-0c859c80-e81d-11ea-932b-67d76a1d6f0c.png">
The docs only mention an abort parameter in the return object for custom functions. Are there any other parameters or callbacks too?
What if I want to do some task after the custom function such as `process` is done?

<br><br>
This issue tracker is intended to collect bug reports and feature requests.

For help with integrating FilePond, information on how features work, or questions about specific features of FilePond, please use [Stack Overflow](https://stackoverflow.com/questions/tagged/filepond). Any issues open for help requests will be closed to keep from clogging up the issue tracker.

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

If your issue can be classified as an integration question or a question about specific features of FilePond we ask you kindly to submit it on [Stack Overflow](https://stackoverflow.com/questions/tagged/filepond).

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the template is not filled out or if the issue is determined to be a question.

**Comment by subodhk01** [comment]
Added the template content, is this the thing what was required?

**Comment by rikschennink** [comment]
When you click "new issue" the textfield contains a template for your to fill in.

**Comment by subodhk01** [comment]
I'm sorry I cannot see any textfield when I click "new issue"

**Comment by rikschennink** [comment]
"New issue" choose the issue type, then where you type the issue description should be a prefill text

**Comment by subodhk01** [comment]
Actually I selected **Questions and help** issue template

**Comment by rikschennink** [comment]
Then, as can be read in the issue template, you should ask your question on Stack Overflow.

See the template below:

> This issue tracker is intended to collect bug reports and feature requests.

> For help with integrating FilePond, information on how features work, or questions about specific features of FilePond, please use [Stack Overflow](https://stackoverflow.com/questions/tagged/filepond). Any issues open for help requests will be closed to keep from clogging up the issue tracker.

**Comment by subodhk01** [comment]
✌🏻
