### ISSUE TITLE
Change hidden inputs name

### ISSUE THREAD

**Issue by wailashraf71** [pqina/filepond#567]
I'm trying to structure my request like **Color->Images[]** so I need to change the hidden input **name** attribute, how can I do that with Filepond Vue?

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

If your issue can be classified as an integration question or a question about specific features of FilePond we ask you kindly to submit it on [Stack Overflow](https://stackoverflow.com/questions/tagged/filepond).

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the template is not filled out or if the issue is determined to be a question.
