### ISSUE TITLE
Several instances leads to having several submit.php's, which doesn't work

### ISSUE THREAD

**Issue by benviatte** [pqina/filepond#569]
First of all, many many thanks for this amazing plugin.

I'm trying to make several instances of filepond on the same page, that should lead to different upload directories. I'm using the following code that was suggested on the github page:

```
$('.pond1').filepond({ allowMultiple: true, server: 'my-first-url' });
$('.pond2').filepond({ allowMultiple: true, server: 'my-second-url' });
```

However, having several servers means each server comes with it's own submit.php. But one form can only have one submit button, right? As a result, my files are correctly being uploaded to the tmp directory, but upon submit, nothing more happens. 

Am I doing something wrong?

Cheers!

**Comment by rikschennink** [comment]
Hi, Thanks, glad to hear that!

We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

If your issue can be classified as an integration question or a question about specific features of FilePond we ask you kindly to submit it on [Stack Overflow](https://stackoverflow.com/questions/tagged/filepond).

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the template is not filled out or if the issue is determined to be a question.
