### ISSUE TITLE
Possible to create multiple image upload at single form or page?

### ISSUE THREAD

**Issue by mkraha** [pqina/filepond#585]
Hi, 
Possible to create multiple image uploads at single form or page?
screenshot: https://pasteboard.co/Jv8QraA.png
```
<label>Image 1</label>
<input type="file" name="image1[]">
<hr>
<label>Image 2</label>
<input type="file" name="image2[]">
<hr>
<label>Image 3</label>
<input type="file" name="image3[]">
```

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

If your issue can be classified as an integration question or a question about specific features of FilePond we ask you kindly to submit it on [Stack Overflow](https://stackoverflow.com/questions/tagged/filepond).

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the template is not filled out or if the issue is determined to be a question.

_As this is clearly a question I kindly ask you to post it on stack overflow_
