### ISSUE TITLE
how to change filePond default white background ?

### ISSUE THREAD

**Issue by nightwolf-041** [pqina/filepond#586]
i mean this area...

![Screenshot (1244)](https://user-images.githubusercontent.com/51447528/95680191-8e226580-0be4-11eb-873f-e5ec3a2f91af.png)

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

If your issue can be classified as an integration question or a question about specific features of FilePond we ask you kindly to submit it on [Stack Overflow](https://stackoverflow.com/questions/tagged/filepond).

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the template is not filled out or if the issue is determined to be a question.

_as this is clearly a question, I kindly ask you to post it on stack overflow or to inspect the docs_
