### ISSUE TITLE
When filepond uses the load method, it inconsistently will use the source id or the file name ContentDisposition Header Value.

### ISSUE THREAD

**Issue by starwarskidfan** [pqina/filepond#596]
**Describe the bug**
When filepond is set with initial files. It calls the load method.

When that method is called sometimes it will populate with the file name from the ContentDisposition Header Value. While other times it just uses the source id

**Logs**
General
Request URL: https://domainname.com/api/v2/file?json=%7BGuid%3A%20%276aae318f-54ad-4ecf-85b0-4b489a00ce67%27%2C%20FileId%3A608%20%7D
Request Method: GET
Status Code: 200 
Remote Address: 172.16.2.26:443
Referrer Policy: strict-origin-when-cross-origin
**Response Headers**
access-control-allow-origin: http://localhost:4200
access-control-expose-headers: Content-Disposition, Content-Length, X-Content-Transfer-Id
cache-control: no-cache
content-disposition: inline; name=tmcLive.png; filename=tmcLive.png; filename*=utf-8''tmcLive.png
content-length: 72913
content-type: image/png
date: Mon, 26 Oct 2020 14:05:39 GMT
expires: -1
pragma: no-cache
server: Microsoft-IIS/10.0
status: 200
x-aspnet-version: 4.0.30319
x-powered-by: ASP.NET
**Request Headers**
:authority: domainname.com
:method: GET
:path: /api/v2/file?json=%7BGuid%3A%20%276aae318f-54ad-4ecf-85b0-4b489a00ce67%27%2C%20FileId%3A608%20%7D
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
origin: http://localhost:4200
pragma: no-cache
referer: http://localhost:4200/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
**Query String Parameters**
json: {Guid: '6aae318f-54ad-4ecf-85b0-4b489a00ce67', FileId:608 }

**Expected behavior**
It should always use the filename from the ContentDisposition Header Value.

**Information about your project:**
- Chrome 86.0.4240.111

- Windows 10

-"filepond": "^4.21.1",
"ngx-filepond": "^5.0.1"

**Additional context**

**Comment by rikschennink** [comment]
Please provide a working and concise test case.

**Comment by starwarskidfan** [comment]
@rikschennink, the code that I have right now is protected by an NDA, so give me a bit to come up with a test environment

**Comment by harshpatel1692** [comment]
It would be great if this could be solved quickly. recently integrated doka + filepond and stuck with this for 2 days until I came across this ticket.

**Comment by rikschennink** [comment]
@harshpatel1692 feel free to contact me using the support form on the customer portal

**Comment by harshpatel1692** [comment]
Let me know if this test case helps.

**Filepond Instance**
`FilePond.create(
	document.getElementById('upload-images'),
	{
		
		files: [
			{
				source: 'http://yourserver.com/file-with-server-id.jpg', //url to fetch image from server
				options: {
					type: 'local'
				}
			}
		
		],
		server: {
			load: (source, load, error, progress, abort, headers) => {
				
				const myRequest = new Request(source);
				fetch(myRequest).then(function(response) {
					console.log(response)
					response.blob().then(function(myBlob) {
						load(myBlob)
					});
				});
			},
		}

	}
)`

**Min Response Headers**
access-control-allow-origin: *
access-control-expose-headers: Content-Disposition, Content-Length, X-Content-Transfer-Id
content-disposition: inline; filename=file-with-original-name.jpg;

**Expected behavior**
The file name should be 'file-with-original-name.jpg' from content-disposition Headers value and **NOT** 'file-with-server-id.jpg'

**Information about your project:**
- FilePond 4.23.1
- Windows 10
- Server URL from Cloudfront/S3
- Google Chrome - 86.0.4240.111

Novice at reverse engineering but below is my finding:

https://github.com/pqina/filepond/blob/ecbc3b1d46842a3be45f8b379cd30714375cd145/src/js/app/utils/createFileLoader.js#L79
response.name gets set to undefined and results in fetching name from the URL.
I tried doing something like this and it reads hard coded name when file is loaded
`if (response instanceof Blob) {
      response = getFileFromBlob(
                        response, 
                        'this-is-broken.jpg' || getFilenameFromURL(url)
       );
}`

**Comment by harshpatel1692** [comment]
Let me know if this test case helps.

**Filepond Instance**
`FilePond.create( document.getElementById('upload-images'),
	{
		files: [
			{
				source: 'http://yourserver.com/file-with-server-id.jpg',
				options: {
					type: 'local'
				}
			}
		],
		server: {
			load: (source, load, error, progress, abort, headers) => {
				const myRequest = new Request(source);
				fetch(myRequest).then(function(response) {
					console.log(response)
					response.blob().then(function(myBlob) {
						load(myBlob)
					});
				});
			}
		}
	}
)`

**Min Response Headers**
access-control-allow-origin: *
access-control-expose-headers: Content-Disposition, Content-Length, X-Content-Transfer-Id
content-disposition: inline; filename=file-with-original-name.jpg;

**Expected behavior**
The file name should be 'file-with-original-name.jpg' from content-disposition Headers value and **NOT** 'file-with-server-id.jpg'

**Information about your project:**
- FilePond 4.23.1
- Windows 10
- Server URL from Cloudfront/S3
- Google Chrome - 86.0.4240.111

Novice at reverse engineering but below is my finding:

response.name gets set to undefined and results in fetching name from the URL.
https://github.com/pqina/filepond/blob/ecbc3b1d46842a3be45f8b379cd30714375cd145/src/js/app/utils/createFileLoader.js#L79

`'this-is-broken.jpg' || getFilenameFromURL(url)`
I tried doing something like this and it reads hard coded name when file is loaded.

**Comment by rikschennink** [comment]
@harshpatel1692 FilePond will get the filename from the content disposition header _only_ if you pass a URL to the `server` prop or one of it's "sub" properties.

In your demo you're using `fetch` to get the file from the URL, the response is then turned into a `Blob`, a `Blob` does not have a `name` property. You need to add it in your custom `load` method.

```js
FilePond.create( document.getElementById('upload-images'),
	{
		files: [
			{
				source: 'http://yourserver.com/file-with-server-id.jpg',
				options: {
					type: 'local'
				}
			}
		],
		server: {
			load: (source, load, error, progress, abort, headers) => {
				const myRequest = new Request(source);
				fetch(myRequest).then(function(response) {
					console.log(response)
					response.blob().then(function(myBlob) {
					        
					        // add name prop here
					        myBlob.name = 'filename.extension'

						load(myBlob)
					});
				});
			}
		}
	}
)
```

**Comment by harshpatel1692** [comment]
@rikschennink Thanks for clarification. can you please elaborate or point me to the documentation on "pass a URL to the server prop or one of it's "sub" properties".

**Comment by rikschennink** [comment]
@harshpatel1692 https://pqina.nl/filepond/docs/patterns/api/server/#configuration

```js
FilePond.setOptions({
    server: './'
});
```

or 

```js
FilePond.setOptions({
    server: {
        process: './process',
        revert: './revert',
        restore: './restore/',
        load: './load/',
        fetch: './fetch/'
    }
});
```

or

```js
FilePond.setOptions({
server:{
    url: 'http://192.168.0.100',
    process: './process',
    revert: './revert',
    restore: './restore/',
    load: './load/',
    fetch: './fetch/'
});
```

more elaborat example

```js
FilePond.setOptions({
    server: {
        url: 'http://192.168.0.100',
        timeout: 7000,
        process: {
            url: './process',
            method: 'POST',
            headers: {
                'x-customheader': 'Hello World'
            },
            withCredentials: false,
            onload: (response) => response.key,
            onerror: (response) => response.data,
            ondata: (formData) => {
                formData.append('Hello', 'World');
                return formData;
            }
        },
        revert: './revert',
        restore: './restore/',
        load: './load/',
        fetch: './fetch/'
    }
});
```

In all these examples FilePond will run the request and handle the data. When you set up a custom method you need to feed the correct file data to FilePond (you take over the wheel).

**Comment by rikschennink** [comment]
Related
https://github.com/pqina/react-filepond/issues/122
