### ISSUE TITLE
Can't use "multiple" option.

### ISSUE THREAD

**Issue by IL4Miy** [pqina/filepond#6]
I'm using [this](https://codepen.io/rikschennink/pen/WXavEx) example in my electron-vue app. I should be able to upload multiple files.
This is shown: <img width="908" alt="bildschirmfoto 2018-03-16 um 23 01 17" src="https://user-images.githubusercontent.com/6071634/37546627-f8865f82-296d-11e8-987a-0af59ddfcf1a.png">

But I expected this:
<img width="354" alt="bildschirmfoto 2018-03-16 um 23 02 58" src="https://user-images.githubusercontent.com/6071634/37546683-335ead12-296e-11e8-8efa-40f80fa660e0.png">

So I can't upload multiple files.
I tried to: 
- reinstall the npm package
- set the "multiple" attribute from code
- remove all .css dependencies
- checked other examples with "multiple".

I'm using macOS HighSierra, filepond version 1.2.0, vue.js and electron.
My code is:
`<input type="file"
    class="filepond"
    name="filepond"
    multiple
    data-max-file-size="3MB"
    data-max-files="3">`

and the call from the vue component: 
`  mounted() {
    FilePond.parse(document.body);
  }`

**Comment by rikschennink** [comment]
I'm not sure how Vue modifies the HTML before it's parsed by FilePond (my guess is that's where the problem lies). Maybe it needs to be `multiple="multiple"` or `multiple="true"` but I would advice to go another route.

The React wrapper creates the instance from JavaScript using the FilePond object `create` method. I would advise doing the same with Vue. Pass options using JavaScript instead of data attributes.

```js
const pond = FilePond.create( inputElement, {
    maxFiles: 10,
    maxFileSize: '3MB',
    allowMultiple: true
});
```

Or create it without an input element and manually append it to the DOM.

```js
const pond = FilePond.create({
    maxFiles: 10,
    maxFileSize: '3MB',
    allowMultiple: true
});

```
The root node can be found in `pond.element`

**Comment by IL4Miy** [comment]
@rikschennink Perfect.
I already tried your approach, but I used the property **multiple** instead of **allowMultiple**.
It's working now.

**Comment by TahaSadikot** [comment]
I am using same in my PHP project can please guide me how can i  get information of uploaded file in PHP script
