### ISSUE TITLE
Problem with resizing BIG images on Android

### ISSUE THREAD

**Issue by fisketavlingnu** [pqina/filepond#604]
**Describe the bug**
The application is a competion report where you provide two pictures. The pictures are resized before transfered to the server.
The problem are images taken with state of the art phones like Samsung S20 in full resolution. These images are sometimes 15MB but even images as small as 6.7MB causes some problems. 

I have set the limit to 16 MB. The problem is that the image transform work on chrome on my windows 10 machine but the image **never finishes on android phones** (I have not tried IOS).

**Logs**
This is the browser console from the android phone:
![image](https://user-images.githubusercontent.com/53155624/97908940-aef35c00-1d47-11eb-955f-1d4aa84c6176.png)
The message "uncaught type error" is pointing on line 49 in this:
![image](https://user-images.githubusercontent.com/53155624/97909352-5f616000-1d48-11eb-82fb-75802c8712a1.png)

The messages occur when you add the bigger file.

Code is attached here:

[team_report_fp.php.gz](https://github.com/pqina/filepond/files/5477501/team_report_fp.php.gz)

**To Reproduce**
This image that is 7MB is causing the problem. Please notice that you need to run on an android to reproduce.
Image causing problem.
![20201028_102230](https://user-images.githubusercontent.com/53155624/97909947-4efdb500-1d49-11eb-82c8-6f5102997751.jpg)

**Expected behavior**

The image should be resized and previewed.

**Stacktraces**

-

**Information about your project:**
- Problem exists in both samsung internet and Chrome.
- Android 10
- Latest version of filepond

**Additional context**

**Comment by rikschennink** [comment]
Thanks for the detailed issue report (and attaching a test image)! 

Going to investigate this first thing tomorrow morning 👍

**Comment by fisketavlingnu** [comment]
I did add the plugin to check the size of the image. And got a new error:
![image](https://user-images.githubusercontent.com/53155624/97914643-80c64a00-1d50-11eb-95f1-e2aef39ce46d.png)

**Comment by rikschennink** [comment]
What happens if you set 

imageTransformCanvasMemoryLimit

To 

4096 * 4096

**Comment by fisketavlingnu** [comment]
Actually now it looks like it is working. I will do some more testing...

**Comment by rikschennink** [comment]
It resizes the initial image data before FilePond goes to work on it. It normally only has to do this for iOS because it cannot load more than (I believe around) 12 mega pixels of data to the canvas element. Not sure what the limit is for Android and/or this is because of canvas or another browser api memory limit but at least this is a quick workaround.

**Comment by rikschennink** [comment]
Best approach might be to set the upper limit to 8096x8096 in case of non-ios, does that still work?

**Comment by Tofandel** [comment]
For me it seems to be happening but only for Samsung internet users (Got this info with sentry monitoring) so it does seem Samsung internet puts some memory limit to its browser

**Comment by rikschennink** [comment]
@Tofandel Thanks for the PR will look into this asap.

**Comment by rikschennink** [comment]
Hi, best to set `imageTransformCanvasMemoryLimit` property to `4096 * 4096`

I'm not sure if this issue is related to Samsung Internet (v14 === Chromium 87) 

You can test the maximum canvas size for a browser here:
https://pqina.nl/pintura/test/canvas/

This is iOS on iPhone 12 mini
<img width="384" alt="Screenshot 2021-07-08 at 11 23 42" src="https://user-images.githubusercontent.com/1132575/124898167-3aac3f00-dfdf-11eb-8381-e6d05e537b0c.png">

This is Samsung Internet on Galaxy S8

<img width="326" alt="Screenshot 2021-07-08 at 11 24 36" src="https://user-images.githubusercontent.com/1132575/124898183-3e3fc600-dfdf-11eb-829e-74ca54d0cc1f.png">

**Comment by rikschennink** [comment]
Closed because inactive.
