### ISSUE TITLE
Can I set to upload one file at at time

### ISSUE THREAD

**Issue by VladG1986** [pqina/filepond#608]
Hello, is there an option to set 1 upload at a time with multiple images?

Example: users can upload up to 10 images. The issue is that first 2 images upload almost at the same time:

2020-11-05 17:44:31.980977732 -0500 EST m=+60.133032415

2020-11-05 17:44:31.996447309 -0500 EST m=+60.148501975

2020-11-05 17:44:34.184205773 -0500 EST m=+62.336260455

2020-11-05 17:44:36.491500178 -0500 EST m=+64.643554850

**Comment by rikschennink** [comment]
You can set `maxParallelUploads` to `1`

---

We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

If your issue can be classified as an integration question or a question about specific features of FilePond we ask you kindly to submit it on [Stack Overflow](https://stackoverflow.com/questions/tagged/filepond).

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the template is not filled out or if the issue is determined to be a question.

**Comment by VladG1986** [comment]
Thank you very much.
