### ISSUE TITLE
Tap to cancel not working

### ISSUE THREAD

**Issue by lucvanrooyen** [pqina/filepond#627]
Hey guys I am quite stuck at the moment - I have override the process method however on my front end whenever I click ''Tap to cancel" - nothing happens. I have tried logging in various places but none of them get hit - can you assist?

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

If your issue can be classified as an integration question or a question about specific features of FilePond we ask you kindly to submit it on [Stack Overflow](https://stackoverflow.com/questions/tagged/filepond).

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the template is not filled out or if the issue is determined to be a question.

**Comment by lucvanrooyen** [comment]
Cool question asked on stackoverflow
