### ISSUE TITLE
FilePond through CDN + Alpine.js = translation ?

### ISSUE THREAD

**Issue by alucard29** [pqina/filepond#630]
Hi and thank you for this wonderful tool.

I already use FilePond through CDN and Alpine.js in a Laravel context but i'm not able to use translations. Does anyone already perform that (is it at least feasible ?)

Regards !

**Comment by rikschennink** [comment]
Thanks for using it!

---

Please note that we require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

If your issue can be classified as an integration question or a question about specific features of FilePond we ask you kindly to submit it on Stack Overflow and tag it with "filepond".

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the template is not filled out or if the issue is determined to be a question.
