### ISSUE TITLE
onprocessfiles not running after preloading images

### ISSUE THREAD

**Issue by alfredasare** [pqina/filepond#634]
I tried preloading images from a remote server. The images do load just fine, but `onprocessfiles` does not run after I add and process new images. `onprocessfile` does run for each image but `onprocessfiles` does not run after they're all done. When I removed the array of preloaded images, `onprocessfiles` run.

![Screenshot (176)](https://user-images.githubusercontent.com/38125880/103289475-3aebd200-49df-11eb-88c0-95b6af3f8229.png)

![Screenshot (174)](https://user-images.githubusercontent.com/38125880/103289489-42ab7680-49df-11eb-848d-088c487259f6.png)

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

If your issue can be classified as an integration question or a question about specific features of FilePond we ask you kindly to submit it on [Stack Overflow](https://stackoverflow.com/questions/tagged/filepond).

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the template is not filled out or if the issue is determined to be a question.
