### ISSUE TITLE
Support contract

### ISSUE THREAD

**Issue by tomaswallentinus** [pqina/filepond#656]
The  "Developer Support Packages" on https://pqina.nl/filepond/#support is gone. If I want to know that Filepond will be maintained in a couple of years it has to be a commercial part of it. Is the support package temporarily gone or is there an alternative route to commit to the framework?

Regards Tomas

**Comment by rikschennink** [comment]
It’s gone because there was literally zero interest in it.

If you want to support the project feel free to sponsor (see link at the top).

Or better yet treat yourself to a [Doka Image Editor](https://pqina.nl/doka/) license. Lots of Doka Image Editor customers use it with FilePond so as long as Doka is financed FilePond will be maintained.

**Comment by tomaswallentinus** [comment]
Great, will do the second. Upload is an important part of our page so we need it to be long term :)
