### ISSUE TITLE
Drag and Drop reorder possible, but not seeing documentation for it.

### ISSUE THREAD

**Issue by brentscholl** [pqina/filepond#660]
When I use the image preview plugin I can drag and drop the order of the images in filepond. However, I am unable to find documentation on this features. 

I'm using file pond for users to upload images to a gallery and the order of the gallery needs to be saved. 

How do I save these images in the order the user sets in filepond using drag and drop reordering? (I'm using Laravel and Livewire)

**Comment by bersyatina** [comment]
Hello, Brentscholl! Look at this screencast here:
https://laravel-livewire.com/screencasts/s8-dragging-list
At the end there is a function that works with sorting. But the problem, as it seems to me, is not in changing the order of files when dragging, but in the order of transferring files from the client to the server. Each time, the server accepts files in a different order, even during the initial save. I also try to set up this bundle and so far it turns out poorly. If you can figure it out, please let me know.

**Comment by brentscholl** [comment]
Not sure if this is correct, but it seems to work

I added this to `FilePond.setOptions()`

```
FilePond.setOptions({
                allowMultiple: true,
                allowReorder: true,
                server: {
                    process: (fieldName, file, metadata, load, error, progress, abort, transfer, options) => {
                        @this.upload('images', file, load, error, progress)
                    },
                    revert: (filename, load) => {
                        @this.removeUpload('images', filename, load)
                    },
                },

                // Added this ----------------------------------------
                onreorderfiles(files, origin, target){
                    @this.set('images', null);
                    files.forEach(function(file) {
                        @this.upload('images', file.file);
                    });
                },
            });
```
This removes the previous uploaded images and reuploads with the new order.

**Comment by rikschennink** [comment]
Closed because inactive.

**Comment by flexchar** [comment]
Hey @brentscholl, would you mind sharing your server side code for Livewire component using Pond? ;)
