### ISSUE TITLE
FilePond:updatefiles is always triggered twice on file-drop

### ISSUE THREAD

**Issue by animaux** [pqina/filepond#668]
**Describe the bug**

When dragging Files onto FilePond, `FilePond:updatefiles` is triggered twice.

**To Reproduce**

https://codesandbox.io/s/vanilla-filepond-forked-shyr6?file=/src/index.js

See `console.log()`.

**Expected behavior**

I would expect it to be triggered only once.

**Information about your project:**

- Your browser and the version: Safari 14.0.3
- Your operating system:  MacOS 11.2
- FilePond version 4.25.1

**Comment by rikschennink** [comment]
Hey! It's currently called for adding files, removing files, and when files finish loading.

**Comment by animaux** [comment]
Thanks for clarification Rik. So there is currently no event that is triggered *only once**, after one or more files have been added?

**Comment by rikschennink** [comment]
Possibly `addfilestart`

**Comment by animaux** [comment]
Thanks, I’ll have a look!

**Comment by majortom64** [comment]
After a user selects or drops files on the drop zone, I want to be able to cycle through the list and generate a summary:

    You are about to upload XXX files with a total size of YYY bytes.

(as well as optionally summaries by file type.)
    
and then displaying a start upload button (for various reasons we don't want files uploaded without approval).

I had planned to use updatefiles but since that is called twice for each addition, it seems like a bad solution. I am not clear if addfile and removefile are called by FilePond for each file added/removed, or if those would be called by my code to add or remove files.

Is there an easy way to accomplish what I am trying to do?
