### ISSUE TITLE
In multiple file upload , simultaneously only 2 files are uploading and rest of the files are in pending status ,its causing my whole upload slower , is ther any way to upload minimum 20 files at same time ?

### ISSUE THREAD

**Issue by KbnCodes** [pqina/filepond#726]
i have more than 500 files to upload , in filepond multiple upload its uploading 2 files at a time thats taking more time to upload , so is there any feature that can change this option ?

**Comment by rikschennink** [comment]
Please read docs → `maxParallelUploads `

We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

Your issue can be classified as an integration question or a question about specific features of FilePond we ask you kindly to submit it on [Stack Overflow](https://stackoverflow.com/questions/tagged/filepond).

**Comment by vesper8** [comment]
@rikschennink I see the default value for `maxParallelUploads` is `null`. What does this mean exactly? My uploads are very slow, I suspect it's because of animations, but I've now changed `maxParallelUploads` to `4` because this is a very common scenario, people picking 4 images at once to upload. Wondering if I might see a small improvement from the default value of `null`.

**Comment by rikschennink** [comment]
@vesper8 it should be `2` this is a documentation error.
