### ISSUE TITLE
Replace the arrow with a cross

### ISSUE THREAD

**Issue by DesWurstes** [pqina/filepond#74]
What really confuses me is that my instincts look for a cross to remove an item, but it's an arrow.

![screenshot_2018-07-01 easy file uploading with javascript filepond](https://user-images.githubusercontent.com/23437045/42137294-955cc1c2-7d72-11e8-81bd-c248a8b02d4c.png)

I'd be more comfortable if it was (shadow is a mistake):

![screenshot_2018-07-01 easy file uploading with javascript filepond copy](https://user-images.githubusercontent.com/23437045/42137296-982aebea-7d72-11e8-9697-73f7d2510600.png)

**Comment by rikschennink** [comment]
I agree that when `instantUpload` is set to `true` it's probably more intuitive if the icon is a cross and the text says `"tap to remove"` instead of `"tap to undo"`. I'll add this to the roadmap.

In the mean time, you can [change the icons](https://pqina.nl/filepond/docs/patterns/api/style/#changing-icons) using FilePond instance properties.

For some very nice looking items, take a look at [Feathericons](https://feathericons.com)

**Comment by rikschennink** [comment]
Now available in version `2.0.0`, text remains `"tap to undo"` but icon is automatically replaced with a cross (the icon set to remove button).

**Comment by DesWurstes** [comment]
Nice, thanks!
