### ISSUE TITLE
Is project actively maintain?

### ISSUE THREAD

**Issue by ccfiel** [pqina/filepond#912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I have noticed a lot of PR are pending and last code commit was January. Is this project actively maintain?

### Describe the solution you'd like

NA

### Describe alternatives you've considered

NA

**Comment by rikschennink** [comment]
It’s maintained but only sparingly at this point.

I’ve not merged a lot of PRs because I don’t want to introduce breaking
changes / aren’t comfortable with potential unknown side effects. This is
mostly my own doing, I should’ve written more tests. People can of course
fork and use a different version of the library.

I’m working on the next version of the library in which I’m trying to
address lots of core issues with v4.
