### ISSUE TITLE
Image Preview not showing when error

### ISSUE THREAD

**Issue by hmalaud** [pqina/filepond#96]
### Summary
When uploading an image that exceeds the max total file size, the preview thumbnail is not generated.
In case of multiple uploads, when removing previous files, errored images are not updated and are still considered as errors.
...

### How to reproduce
Register FilePondPluginImagePreview and FilePondPluginFileValidateSize plugins
Create pond with max-total-file-size="2MB"
Upload 1MB image -> ✔️ OK
Upload 1.5MB image -> ✔️ Image is uploaded as errored BUT ✖️ preview thumbnail is not generated
Remove 1MB image -> ✔️ Image is removed BUT ✖️ 1.5MB image is still considered as an error
https://codepen.io/bigjohnbigd/pen/PBxBMe

...

### Expected behaviour
Images should show the preview even if errored OR images with an error should be updated when removing files

...

| Environment  | Version
|------------- | -----------
| OS           | MacOS
| Device       | MacBookPro 2017 13"
| Browser      | Chrome/Firefox...

**Comment by rikschennink** [comment]
If an image is invalid whether it's invalid because the image itself is not suitable or the total file size is exceeded it is not loaded. Therefore the image data is not available for the image preview to load.

Some error messages like the total file size exceeded error message are currently shown on the item that exceeds the limit. This I feel can be improved as the error in this situation concerns the entire list of files. I'll probably introduce a new error location for these situations in the future. For now, the current behavior will stay the same.
