### ISSUE TITLE
Resize single image while maintaining the size of others

### ISSUE THREAD

**Issue by peterbrinck** [pqina/filepond#97]
Hi!

How do I resize a single image, while maintaining the original size of the other images?

I'm using the `image-resize` plugin, but as far as I can see, it can only resize all images.  
I want to be able to pick an image to resize

**Comment by rikschennink** [comment]
Hi, This is not possible, it will either resize all images or none. You'd have to create two separate drop areas.

**Comment by peterbrinck** [comment]
Hmm... Okay

Thank you for the quick answer

**Comment by exninja** [comment]
@peterbrinck 

If you're using Vue (not stated), there is a workaround to select dynamic size, but you'd need to pass them in to your FilePond child component as a prop. i.e. use a dropdown or radio button group to select the size on your parent, then pass the size in as a prop. I do this so that my FilePond is re-useable across various scenarios.

```
    props: [
        ...
        'imagePreviewHeight',
        'imageCropAspectRatio',
        'imageResizeTargetWidth',
        'imageResizeTargetHeight',
        'imageResizeMode',
        'stylePanelLayout',
        ...
    ]
```

```
        :image-preview-height="imagePreviewHeight"
        :image-crop-aspect-ratio="imageCropAspectRatio"
        :image-resize-target-width="imageResizeTargetWidth"
        :image-resize-target-height="imageResizeTargetHeight"
        :image-resize-mode="imageResizeMode"
        :style-panel-layout="stylePanelLayout"
        :instant-upload="instantUpload"
```
